library("tidyverse")
library("palmerpenguins")
univar_plot <- ggplot(data=penguins,aes(x=flipper_length_mm))+xlab("Flipper length (mm)")
univar_plot+geom_histogram(binwidth=5)+ylab("Count")
univar_plot+geom_density(adjust=0.5)+ylab("Density")
ggplot(data=penguins,aes(x=flipper_length_mm,color=species))+geom_density()+xlab("Flipper length (mm)")+ylab("Density")
ggplot(data=penguins,aes(x=species,y=flipper_length_mm))+geom_boxplot()+xlab("Penguin species")+ylab("Flipper length (mm)")
ggplot(data=penguins,aes(x=species,y=flipper_length_mm,fill=species))+geom_violin()+xlab("Penguin species")+ylab("Flipper length (mm)")
ggplot(data=penguins,aes(y=body_mass_g,x=flipper_length_mm))+ylab("Body mass (g)")+xlab("Flipper length (mm)")+geom_point(size=3,aes(color=bill_length_mm))+scale_color_gradient(low="blue",high="red")+guides(color=guide_legend("Bill length (mm)"))
ggplot(data=penguins,aes(y=body_mass_g,x=flipper_length_mm))+ylab("Body mass (g)")+xlab("Flipper length (mm)")+geom_point(aes(size=bill_depth_mm))+guides(size=guide_legend("Bill depth (mm)"))
ggplot(data=penguins,aes(y=body_mass_g,x=flipper_length_mm))+ylab("Body mass (g)")+xlab("Flipper length (mm)")+geom_point(aes(shape=species))+guides(shape=guide_legend("species"))
ggplot(data=penguins,aes(y=body_mass_g,x=flipper_length_mm))+ylab("Body mass (g)")+xlab("Flipper length (mm)")+geom_point()+facet_wrap(~species)
ggplot(data=filter(penguins,species=="Gentoo"),aes(y=body_mass_g,x=flipper_length_mm))+ylab("Body mass (g)")+xlab("Flipper length (mm)")+geom_point()+geom_smooth()
ggplot(data=filter(penguins,species=="Gentoo"),aes(y=body_mass_g,x=flipper_length_mm))+ylab("Body mass (g)")+xlab("Flipper length (mm)")+geom_point()+geom_smooth(method="lm")
ggplot(data=filter(penguins,species=="Gentoo"),aes(y=body_mass_g,x=flipper_length_mm))+ylab("Body mass (g)")+xlab("Flipper length (mm)")+geom_point()+geom_smooth(method="lm")
ggplot(data=filter(penguins,species=="Gentoo"),aes(y=body_mass_g,x=flipper_length_mm))+ylab("Body mass (g)")+xlab("Flipper length (mm)")+geom_point()+geom_smooth(method="lm")+geom_curve(x=220,xend=209,y=4250,yend=3975,arrow=arrow(length=unit(0.5,"cm")),curvature=0.1)+geom_text(x=225,y=4250,label="The lightest Gentoo \n penguin weighs 39.5kg")
